development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4dc8f698774c1dbd6aab249f84abeac4@viperfish.redistogo.com:10502/ # production

staging:
  adapter: redis
  url: redis://redistogo:6b3ef86221c09da50f1b056d3140001f@crestfish.redistogo.com:11821/ # staging
